---
- name: Docker Setup and Installation
  hosts: docker
  tasks:
    - name: Update cache and dependencies
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Install keyrings
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - name: Add repository
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Update cache again :)
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Docker components
      ansible.builtin.apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - dontainerd.io
        - docker-buildx-plugin
        - docker-compose-plugin