---
- name: update ssh keys
  hosts: all
  tasks:
    - name: Set authorized keys, removing all the authorized keys already set
      ansible.posix.authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - ~/.ansible/public_keys/simon
        - ~/.ansible/public_keys/gordon
        - ~/.ansible/public_keys/tobias
        - ~/.ansible/public_keys/alex
    - name: Disable password-authentication for ssh
      shell: sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
    - name: reload sshd service
      ansible.builtin.service:
        name: sshd
        state: reloaded
