---
- name: GlusterFS Installation and Configuration
  hosts: docker
  tasks:
    - name: Update Repos
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
    - name: Edit hosts file
      ansible.builtin.blockinfile: 
        state: present
        insertafter: EOF
        dest: /etc/services
        marker: "<!-- add services ANSIBLE MANAGED BLOCK -->"
        content: |
          ####################
          # glusterfs-server #
          ####################
          192.168.0.41 node1
          192.168.0.42 node2
          192.168.0.43 node3
          192.168.0.44 node4
          192.168.0.45 node5
    - name: Install GlusterFS
      ansible.builtin.apt:
        name: glusterfs-server
        state: present
    - name: Start and Enable GlusterFS
      ansible.builtin.service:
        name:   glusterd
        state: started
        enabled: yes
    - name: Check glusterd status
      shell: systemctl status glusterd
    - name: Create xfs filesystem
      community.general.filesystem:
        fstype: xfs
        dev: /dev/sdb1
    - name: Create gluster mount-mount-dir
      shell: mkdir /mnt/gluster
    - name: add glusterd-disk to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: /dev/sdb1 /mnt/gluster xfs defaults 0 0
        create: yes
    - name: mount disks
      shell: mount -a
